# yaml-language-server: $schema=https://github.com/n0rad/base-helm-chart/releases/download/base-1.250501.709-Heffe9b6/values-helmRelease.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pushprox
  namespace: prometheus
spec:
  interval: 60m
  chart:
    spec:
      chart: base-template
      version: 1.250501.709-Heffe9b6
      sourceRef:
        kind: HelmRepository
        name: base
        namespace: flux-system
  rollback:
    cleanupOnFail: true
  values:
    mainWorkload:
      pod:
        securityContext:
          runAsUser: 65534

      container:
        image:
          repository: quay.io/prometheuscommunity/pushprox
          tag: v0.2.0

      service:
        ports:
          http:
            port: 8080

      ingress:
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: traefik-authelia-basic@kubernetescrd
          kubernetes.io/tls-acme: "true"
        hosts:
          - host: pushprox.${BCL_GLOBAL_DOMAIN}
            paths:
              - path: /
                service:
                  name: pushprox
                  port: 8080
                pathType: ImplementationSpecific
        tls:
          - secretName: tls-pushprox
            hosts:
              - pushprox.${BCL_GLOBAL_DOMAIN}
