# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno-config
  namespace: bcl
spec:
  interval: 10m
  timeout: 1m
  path: ./kube/apps/kyverno-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: bcl
  wait: true
  dependsOn:
    - name: kyverno
  postBuild:
    substituteFrom:
      - name: global-env
        kind: ConfigMap
