# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-config
  namespace: longhorn-system
spec:
  interval: 1h
  path: ./kube/apps/longhorn/longhorn-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: bcl
  wait: true
