apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authelia
  namespace: traefik
spec:
  forwardAuth:
    address: 'http://authelia.authelia.svc.cluster.local/api/authz/forward-auth'
    trustForwardHeader: true
    authResponseHeaders:
      - 'Remote-User'
      - 'Remote-Groups'
      - 'Remote-Email'
      - 'Remote-Name'

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authelia-basic
  namespace: traefik
spec:
  forwardAuth:
    address: 'http://authelia.authelia.svc.cluster.local/api/verify?auth=basic'
    trustForwardHeader: true
    authResponseHeaders:
      - 'Remote-User'
      - 'Remote-Groups'
      - 'Remote-Email'
      - 'Remote-Name'
