# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CLI

on:
  push:
    paths:
      - cli/**
      - .github/workflows/cli.yaml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cli

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # whole repo

      - name: Build CLI
        if: github.ref != 'refs/heads/main'
        run: ./gomake build

      - name: Release CLI
        if: github.ref == 'refs/heads/main'
        run: ./gomake release
